title: Jekyll Framework
source: /src/_site
destination: /src/dist
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - disable_indented_code_blocks
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - autolink
    - tables
    - footnotes
highlighter: rouge
permalink: pretty
array: []
include:
  - _assets
exclude:
  - _assets/scss
ga_tracking_id: UA-XXXXX-X
cdn_url: 'http://cdn.com'
